set -sg escape-time 2
set -g extended-keys on

set -g history-limit 50000

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g mouse on
set -g focus-events on

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind -n S-Left previous-window
bind -n S-Right next-window

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

set -g status-position bottom
set -g message-style 'bg=#00e68a fg=#000000 bold'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.3.0'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'

set -g status-right-length 100
set -g status-left-length 100

set -g status-left ""
set -g status-right ""
set -ag status-right "#{E:@catppuccin_status_uptime}"

run '~/.tmux/plugins/tpm/tpm'
