local function map(mode, key, fn, desc)
	vim.keymap.set(mode, key, fn, { noremap = true, silent = true, desc = desc })
end

-- Podstawowe i systemowe
map("n", "<leader>w", "<cmd>w<CR>", "Zapisz plik")
map("n", "<leader>q", "<cmd>q<CR>", "Wyjdź")
map("n", "<leader>cc", "<cmd>e $MYVIMRC<CR>", "Edytuj konfigurację Neovim")
map("i", "<C-s>", "<cmd>write<CR><Esc>", "Zapisz plik (Insert mode)")
vim.api.nvim_create_user_command("W", "w", {})

-- Nawigacja i edycja
vim.keymap.set("n", "j", function()
	return vim.v.count == 0 and "gj" or "j"
end, { expr = true, silent = true, desc = "Down (wrap-aware)" })
vim.keymap.set("n", "k", function()
	return vim.v.count == 0 and "gk" or "k"
end, { expr = true, silent = true, desc = "Up (wrap-aware)" })
map("n", "n", "nzzzv", "Następny wynik szukania (wyśrodkowany)")
map("n", "N", "Nzzzv", "Poprzedni wynik szukania (wyśrodkowany)")
map("n", "<C-d>", "<C-d>zz", "Pół strony w dół (wyśrodkowane)")
map("n", "<C-u>", "<C-u>zz", "Pół strony w górę (wyśrodkowane)")
map("n", "J", "mzJ`z", "Złącz linie bez zmiany pozycji kursora")
map("x", "<leader>p", '"_dP', "Wklej bez nadpisywania schowka")

-- Blokowanie strzałek (dobry nawyk)
map({ "n", "i" }, "<up>", "<nop>", "")
map({ "n", "i" }, "<down>", "<nop>", "")
map({ "n", "i" }, "<left>", "<nop>", "")
map({ "n", "i" }, "<right>", "<nop>", "")

-- Przesuwanie linii tekstu
map("n", "<A-j>", ":m .+1<CR>==", "Przesuń linię w dół")
map("n", "<A-k>", ":m .-2<CR>==", "Przesuń linię w górę")
map("v", "<A-j>", ":m '>+1<CR>gv=gv", "Przesuń zaznaczenie w dół")
map("v", "<A-k>", ":m '<-2<CR>gv=gv", "Przesuń zaznaczenie w górę")
map("v", "<", "<gv", "Wcięcie w lewo i pozostaw zaznaczenie")
map("v", ">", ">gv", "Wcięcie w prawo i pozostaw zaznaczenie")

-- Okna (Splity)
map("n", "<C-h>", "<C-w>h", "Przejdź do lewego okna")
map("n", "<C-j>", "<C-w>j", "Przejdź do dolnego okna")
map("n", "<C-k>", "<C-w>k", "Przejdź do górnego okna")
map("n", "<C-l>", "<C-w>l", "Przejdź do prawego okna")
map("n", "<leader>sv", ":vsplit<CR>", "Podziel okno pionowo")
map("n", "<leader>sh", ":split<CR>", "Podziel okno poziomo")
map("n", "<C-Up>", ":resize +2<CR>", "Zwiększ wysokość okna")
map("n", "<C-Down>", ":resize -2<CR>", "Zmniejsz wysokość okna")
map("n", "<C-Left>", ":vertical resize -2<CR>", "Zmniejsz szerokość okna")
map("n", "<C-Right>", ":vertical resize +2<CR>", "Zwiększ szerokość okna")

-- Buffery
map("n", "<S-l>", ":bnext<CR>", "Następny buffer")
map("n", "<S-h>", ":bprevious<CR>", "Poprzedni buffer")
map("n", "<leader><leader>", "<C-^>", "Ostatni buffer")
map("n", "<leader>bd", ":bd<CR>", "Zamknij buffer")
map("n", "<leader>x", ":bd<CR>", "Zamknij buffer (szybki skrót)")

-- Kopiowanie ścieżki
map("n", "<leader>pa", function()
	local path = vim.fn.expand("%:p")
	vim.fn.setreg("+", path)
	print("Skopiowano ścieżkę:", path)
end, "Skopiuj pełną ścieżkę pliku")

-- Snacks Pickery (Twoje ulubione)
map("n", "<leader>ff", function()
	require("snacks").picker.files({ hidden = true })
end, "Znajdź pliki")
map("n", "<leader>fg", function()
	require("snacks").picker.grep({ hidden = true })
end, "Szukaj w plikach (Grep)")
map("n", "<leader>fb", function()
	require("snacks").picker.buffers()
end, "Otwarte buffery")
map("n", "<leader>fh", function()
	require("snacks").picker.tags()
end, "Tagi pomocy")
map("n", "<leader>e", function()
	require("snacks").explorer.open({ hidden = true })
end, "Eksplorator plików")
map("n", "<leader>E", "<cmd>Yazi<cr>", "Otwórz Yazi")
map("n", "<leader>-", "<cmd>Yazi toggle<cr>", "Wznów Yazi")
map("n", "<leader>gg", function()
	require("snacks").lazygit()
end, "Lazygit")
map({ "n", "t" }, "<C-_>", function()
	require("snacks").terminal.toggle()
end, "Przełącz terminal")
map({ "n", "t" }, "<C-/>", function()
	require("snacks").terminal.toggle()
end, "Przełącz terminal")

-- Narzędzia / LSP
map("n", "gd", function()
	require("snacks").picker.lsp_definitions()
end, "Idź do definicji")
map("n", "gS", function()
	vim.cmd("vsplit")
	vim.lsp.buf.definition()
end, "Definicja (nowy split)")
map("n", "<leader>ca", vim.lsp.buf.code_action, "Code action")
map("n", "<leader>rn", vim.lsp.buf.rename, "Zmień nazwę (Rename)")
map("n", "<leader>cf", function()
	vim.lsp.buf.code_action({ context = { only = { "source.organizeImports" }, diagnostics = {} }, apply = true })
	vim.defer_fn(function()
		vim.lsp.buf.format({})
	end, 50)
end, "Organizuj importy i formatuj")
map("n", "<leader>th", function()
	vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end, "Przełącz Inlay Hints")
map("n", "<leader>td", function()
	vim.diagnostic.enable(not vim.diagnostic.is_enabled())
end, "Przełącz Diagnostykę")
map("n", "<leader>d", function()
	vim.diagnostic.open_float({ scope = "cursor" })
end, "Diagnostyka pod kursorem")
map("n", "<leader>D", function()
	vim.diagnostic.open_float({ scope = "line" })
end, "Diagnostyka z całej linii")

-- Trouble
map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", "Diagnostyka (Trouble)")
map("n", "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", "Diagnostyka Buffera (Trouble)")
map("n", "<leader>cs", "<cmd>Trouble symbols toggle focus=false<cr>", "Symbole (Trouble)")
map("n", "<leader>cl", "<cmd>Trouble lsp toggle focus=false win.position=right<cr>", "Definicje / Referencje (Trouble)")

-- Dodatki
map("n", "<leader>fr", function()
	require("grug-far").open()
end, "Szukaj i zamień (Grug Far)")
map("n", "<leader>fp", "<cmd>ProjectSnacks<cr>", "Projekty")
map("n", "<leader>cv", function()
	require("swenv.api").pick_venv()
end, "Wybierz Python venv")
map("n", "s", function()
	require("flash").jump()
end, "Flash Jump")

-- Treesitter selekcja (Zostawiamy Twoje customowe)
map("x", "v", "]", "Rozszerz zaznaczenie Treesitter")
map("x", "V", "[", "Zmniejsz zaznaczenie Treesitter")
