vim.pack.add({
	"https://github.com/windwp/nvim-autopairs",
	"https://github.com/folke/tokyonight.nvim",
	"https://www.github.com/lewis6991/gitsigns.nvim",
	"https://github.com/akinsho/bufferline.nvim",
	"https://github.com/nvim-lualine/lualine.nvim",
	"https://github.com/MagicDuck/grug-far.nvim",
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter", branch = "main", build = ":TSUpdate" },
	"https://www.github.com/neovim/nvim-lspconfig",
	"https://github.com/mason-org/mason.nvim",
	"https://github.com/mason-org/mason-lspconfig.nvim",
	"https://github.com/saghen/blink.lib",
	{
		src = "https://github.com/saghen/blink.cmp",
		build = function()
			require("blink.cmp").build():wait(60000)
		end,
	},
	"https://github.com/L3MON4D3/LuaSnip",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/folke/snacks.nvim",
	"https://github.com/folke/which-key.nvim",
	"https://github.com/folke/flash.nvim",
	"https://github.com/DrKJeff16/project.nvim",
	{ src = "https://github.com/mrcjkb/rustaceanvim", version = vim.version.range("^9") },
	"https://github.com/folke/trouble.nvim",
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/mikavilpas/yazi.nvim",
	"https://github.com/rose-pine/neovim",
	"https://github.com/ellisonleao/gruvbox.nvim",
	"https://github.com/rebelot/kanagawa.nvim",
	"https://github.com/nyoom-engineering/oxocarbon.nvim",
	"https://github.com/mcauley-penney/techbase.nvim",
	"https://github.com/ray-x/lsp_signature.nvim",
	"https://github.com/catppuccin/nvim",
	"https://github.com/stevearc/conform.nvim",
	"https://github.com/echasnovski/mini.nvim",
	"https://github.com/folke/todo-comments.nvim",
	"https://github.com/folke/persistence.nvim",
	"https://github.com/AckslD/swenv.nvim",
})
